Mepts 273 update visit type tranformations
esaude/openmrs-database-migrator pull request #43
Opened 2019-10-23 23:03 UTC by kaweesi

2019-10-23 23:06 UTC, kaweesi commented
unfortunately this lists more commits than it should maybe because i started off this work off a wrong branch that got merged into develop, its merged content however is not listed in the changes https://github.com/esaude/openmrs-database-migrator/pull/43/files

2019-10-24 13:13 UTC, cfaife requested changes

2019-10-24 13:13 UTC, cfaife commented on src/main/resources/pdiresources/visit-type/logging.ktr
> +      <to>form-log</to>
Here I  think  it should be `visit-log`

2019-10-24 13:13 UTC, cfaife commented on src/main/resources/pdiresources/visit-type/logging.ktr
> +    <name>updated forms</name>
the same  here .... I  think it should be `updated visits`

2019-10-24 13:13 UTC, cfaife commented on src/main/resources/pdiresources/visit-type/preparation.ktr
> +    <sql>ALTER TABLE visit ADD column updated INT(1) DEFAULT 0;</sql>
I think it should be placed `updated BOOLEAN DEFAULT 0`, to  avoid other integer values

2019-10-24 13:13 UTC, cfaife commented on src/main/resources/pdiresources/visit-type/preparation.ktr
> +    <hop>
here in the data base connection we should add `set foreign_key_checks=0`; to allow delete statement

2019-10-24 14:09 UTC, cfaife approved these changes

2019-10-24 14:09 UTC, merged